### ISSUE TITLE
New EPDr version for R3.3.3?

### ISSUE THREAD

**Issue by wfinsinger** [dinilu/EPDr#13]
Dear Diego,

Many many thanks for all your work with the EPDr package!!

Just a quick question, I've received a message saying that:
Warning in install.packages :
  package ‘EPDr’ is not available (for R version 3.3.3)

Would be cool of you could build an up-to-date EPDr version compatible with R 3.3.3...

Best wishes,

walt

**Comment by dinilu** [comment]
Since the package is not yet in CRAN, the recommended installation procedure is as follows:
install.packages("devtools") 
library(devtools)
install_github("dinilu/EPDr")
library(EPDr)
help(package=EPDr)
This procedure should compile the package 'on the fly' for the R-version in the computer that is been used.
No need, hence, to build or precompile versions of the package.
I proceed to close the issue.
